export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const GET_USERS = 'GET_USERS';
export const GET_USER = 'GET_USER';
export const SET_CURRENT = 'SET_CURRENT';

export const GET_POSTS = 'GET_POSTS';
export const GET_POSTDETAILS = 'GET_POSTDETAILS';
export const GET_RECENTPOSTS = 'GET_RECENTPOSTS';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_SIMILARPOSTS = 'GET_SIMILARPOSTS';
export const GET_ADJACENTPOSTS = 'GET_ADJACENTPOSTS';
export const GET_CATEGORYPOST = 'GET_CATEGORYPOST';
export const GET_FEATUREDPOSTS = 'GET_FEATUREDPOSTS';
export const GET_COMMENTS = 'GET_COMMENTS';
export const SUBMITCOMMENT = 'SUBMITCOMMENT';
export const FILTER_POSTS = 'FILTER_POSTS';
export const CLEAR_FILTER = 'CLEAR_FILTER';
export const CLEAR_CURRENT = 'CLEAR_CURRENT';
export const POST_ERROR = 'POST_ERROR';

