export const GET_ITEMS = 'GET_ITEMS';
export const GET_PUBLICITEMS = 'GET_PUBLICITEMS';
export const GET_ITEM = 'GET_ITEM';
export const ADD_ITEM = 'ADD_ITEM';
export const DELETE_ITEM = 'DELETE_ITEM';
export const SET_CURRENT = 'SET_CURRENT';
export const CLEAR_CURRENT = 'CLEAR_CURRENT';
export const UPDATE_ITEM = 'UPDATE_ITEM';
export const FILTER_ITEMS = 'FILTER_ITEMS';
export const CLEAR_ITEMS = 'CLEAR_ITEMS';
export const CLEAR_FILTER = 'CLEAR_FILTER';
export const ITEM_ERROR = 'ITEM_ERROR';

export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const SUPPLIER_LOADED = 'SUPPLIER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const GET_SUPPLIERS = 'GET_SUPPLIERS';
export const GET_SUPPLIER = 'GET_SUPPLIER';
export const ADD_SUPPLIER = 'ADD_SUPPLIER';
export const DELETE_SUPPLIER = 'DELETE_SUPPLIER';
export const UPDATE_SUPPLIER = 'UPDATE_SUPPLIER';
export const FILTER_SUPPLIERS = 'FILTER_SUPPLIERS';
export const CLEAR_SUPPLIERS = 'CLEAR_SUPPLIERS';
export const SUPPLIER_ERROR = 'SUPPLIER_ERROR';

export const ADD_CHART = 'ADD_CHART';
export const UPDATE_CHART = 'UPDATE_CHART';
export const DELETE_CHART = 'DELETE_CHART';


export const GET_POSTS = 'GET_POSTS';
export const GET_POSTDETAILS = 'GET_POSTDETAILS';
export const GET_RECENTPOSTS = 'GET_RECENTPOSTS';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_SIMILARPOSTS = 'GET_SIMILARPOSTS';
export const GET_ADJACENTPOSTS = 'GET_ADJACENTPOSTS';
export const GET_CATEGORYPOST = 'GET_CATEGORYPOST';
export const GET_FEATUREDPOSTS = 'GET_FEATUREDPOSTS';
export const GET_COMMENTS = 'GET_COMMENTS';
export const SUBMITCOMMENT = 'SUBMITCOMMENT';

export const POST_ERROR = 'ITEM_ERROR';